apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      helm:
        parameters:
        - name: "namespace"
          value: cert-manager
        - name: "version"
          value: "v1.12.1"
        - name: "installCRDs"
          value: "true"
          forceString: true
    # - repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    #   targetRevision: HEAD
    #   chart: actions-runner-controller
    #   helm:
    #     parameters:
    #     - name: "namespace"
    #       value: actions-runner-controller
    #     - name: "version"
    #       value: "v0.23.3"
    #     - name: "authSecret.create"
    #       value: "true"
    #     - name: "authSecret.github_token"
    #       value: "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"
    #     - name: "githubWebhookServer.enabled"
    #       value: "true"
    # - repoURL: https://github.com/coutug/action-runner
    #   targetRevision: HEAD
    #   path: configs
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true